export const siteConfig = {
  name: "Пантеон Наук",
  domain: "panteon-nauk.org.ua",
  url: "https://panteon-nauk.org.ua",
  language: "uk",
  locale: "uk_UA",
  description: "Дослідницький портал акустики та ергономіки робочого простору. Наукові статті про акустичні кабіни для офісу, звукоізоляційні рішення та офісні кабіни.",
  ogImage: "/images/blog/hero.webp",
  favicon: "/images/favicon.svg",
  keywords: ["акустичні кабіни для офісу", "офісні кабіни", "звукоізоляційні кабіни", "кабіни для переговорів", "акустична кабіна", "звукоізоляція офісу"],
  address: "м. Київ, Україна",
  phone: "",
  email: "info@panteon-nauk.org.ua",
  workingHours: "Пн-Пт: 09:00 - 18:00",
  season: "",
  crmWebhookUrl: "https://office.silent-box.com/api/pbn/webhook",
}
